apiVersion: v1
kind: Pod
metadata:
  name: hello-once
  labels:
    app: hello
spec:
  containers:
  - name: hello
    image: busybox
    command: ["sh", "-c", "echo 'Hello, world!' | nc -l -p 8080 -q 1"]
    ports:
    - containerPort: 8080
  restartPolicy: Never