apiVersion: v1
kind: Pod
metadata:
  name: hello-once
  labels:
    app: hello
spec:
  containers:
  - name: hello
    image: python:3.12-alpine
    command: ["python3", "-c"]
    args:
      - |
        import socket
        s = socket.socket()
        s.bind(('', 8080))
        s.listen(1)
        conn, addr = s.accept()
        req = conn.recv(1024)
        conn.sendall(b"HTTP/1.1 200 OK\r\nContent-Type: text/plain\r\nContent-Length: 13\r\n\r\nHello, world!")
        conn.close()
        s.close()
    ports:
    - containerPort: 8080
  restartPolicy: Never