apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    app: hello
spec:
  containers:
  - name: hello
    image: python:3.12-alpine
    command: ["python3", "-m", "http.server", "8080"]
    ports:
    - containerPort: 8080
