apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hello-rs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: python:3.12-alpine
        command: ["python3", "-m", "http.server", "8080"]
        ports:
        - containerPort: 8080